update 88-dars

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -50,8 +50,8 @@ jobs:
           git pull || { echo "Git pull failed!"; exit 1; }
 
           echo "Installing dependencies..."
-          npm i -g pnpm || { echo "Failed to install pnpm!"; exit 1; }
-          pnpm i || { echo "Dependency installation failed!"; exit 1; }
+          sudo npm install -g pnpm || { echo "Failed to install pnpm!"; exit 1; }
+          pnpm install || { echo "Dependency installation failed!"; exit 1; }
           npm run build || { echo "Build failed!"; exit 1; }
 
           echo "Restarting Docker services..."
